### ISSUE TITLE
myexternalip endpoint change

### ISSUE THREAD

**Issue by brunnels** [stevemcquaid/cloudflare-dyndns#1]
Doesn't look like the ipv4 and ipv6 endpoints for myexternalip.com are working anymore.

https://myexternalip.com/raw still works.

**Comment by stevemcquaid** [comment]
Thanks @brunnels  - just saw this

**Comment by stevemcquaid** [comment]
Fixed for ipv4 here: https://github.com/stevemcquaid/cloudflare-dyndns/commit/05869be36484ccba48f11610cd9669ad24ba0de4
